### ISSUE TITLE
A nasty backtrace when trying to stash even though there are unmerged changes

### ISSUE THREAD

**Issue by d33tah** [aanand/git-up#106]
```
(virtualenv)[3/5/2][21:57:14][~/dotfiles]$ git up        
Fetching origin
stashing 3 changes
Traceback (most recent call last):
  File "/usr/bin/git-up", line 9, in <module>
    load_entry_point('git-up==1.3.0', 'console_scripts', 'git-up')()
  File "/usr/bin/gitup.py", line 589, in run
    gitup.run()
  File "/usr/bin/gitup.py", line 200, in run
    with self.git.stash():
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/site-packages/PyGitUp/git_wrapper.py", line 146, in stash
    self.git.stash()
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 440, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 834, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 627, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git stash' returned with exit code 1
stderr: 'zshrc: unmerged (2123e4b31307745a847515a4bcd128d9039e5285)
zshrc: unmerged (6688213d759d0971e4937b7b6ef422cd1d6f6172)
zshrc: unmerged (10370b3e8b0594511f9c7c82d6d00c8ee21ff87c)
fatal: git-write-tree: error building trees
Cannot save the current index state'
(virtualenv)[3/5/2][21:57:17][~/dotfiles][1] $ git status
# On branch master
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#       modified:   bin-scripts/backtick
#       modified:   vimrc
#
# Unmerged paths:
#   (use "git reset HEAD <file>..." to unstage)
#   (use "git add <file>..." to mark resolution)
#
#       both modified:      zshrc
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       bin-scripts/pvgf
#       vim/.netrwhist
```

**Comment by msiemens** [comment]
@d33tah: Hey, seems like you're using the Python version. This repo is the original Ruby implementation. Please open a ticket at github.com/msiemens/PyGitUp :)

**Comment by d33tah** [comment]
Ah, sorry.
