### ISSUE TITLE
git up fails when upstream branch is deleted

### ISSUE THREAD

**Issue by themactep** [aanand/git-up#108]
```
$ git up
Fetching origin
From https://github.com/pusher/pusher-realtime-chat-widget
 x [deleted]         (none)     -> origin/master
   (refs/remotes/origin/HEAD has become dangling)
remote: Counting objects: 24, done.
remote: Total 24 (delta 7), reused 7 (delta 7), pack-reused 17
Unpacking objects: 100% (24/24), done.
   c341a41..044148e  gh-pages   -> origin/gh-pages
/var/lib/gems/2.1.0/gems/git-up-0.5.12/lib/git-up.rb:95:in `rebase_all_branches': undefined method `+' for nil:NilClass (NoMethodError)
    from /var/lib/gems/2.1.0/gems/git-up-0.5.12/lib/git-up.rb:22:in `block (3 levels) in run'
    from /var/lib/gems/2.1.0/gems/git-up-0.5.12/lib/git-up.rb:199:in `returning_to_current_branch'
    from /var/lib/gems/2.1.0/gems/git-up-0.5.12/lib/git-up.rb:21:in `block (2 levels) in run'
    from /var/lib/gems/2.1.0/gems/git-up-0.5.12/lib/git-up.rb:183:in `with_stash'
    from /var/lib/gems/2.1.0/gems/git-up-0.5.12/lib/git-up.rb:20:in `block in run'
    from /var/lib/gems/2.1.0/gems/grit-2.5.0/lib/grit/git.rb:90:in `with_timeout'
    from /var/lib/gems/2.1.0/gems/git-up-0.5.12/lib/git-up.rb:19:in `run'
    from /var/lib/gems/2.1.0/gems/git-up-0.5.12/bin/git-up:5:in `<top (required)>'
    from /usr/local/bin/git-up:23:in `load'
    from /usr/local/bin/git-up:23:in `<main>'

$ git status
On branch master
Your branch is based on 'origin/master', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)
nothing to commit, working directory clean
```

**Comment by marcoscaceres** [comment]
FWIW, got the same...  also thought I would file it. :heart: git up :)
```
╰─➤  git up
/Library/Ruby/Gems/2.0.0/gems/git-up-0.5.12/lib/git-up.rb:95:in `rebase_all_branches': undefined method `+' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/git-up-0.5.12/lib/git-up.rb:22:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/git-up-0.5.12/lib/git-up.rb:199:in `returning_to_current_branch'
	from /Library/Ruby/Gems/2.0.0/gems/git-up-0.5.12/lib/git-up.rb:21:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/git-up-0.5.12/lib/git-up.rb:183:in `with_stash'
	from /Library/Ruby/Gems/2.0.0/gems/git-up-0.5.12/lib/git-up.rb:20:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/grit-2.5.0/lib/grit/git.rb:90:in `with_timeout'
	from /Library/Ruby/Gems/2.0.0/gems/git-up-0.5.12/lib/git-up.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/git-up-0.5.12/bin/git-up:5:in `<top (required)>'
	from /usr/local/bin/git-up:23:in `load'
	from /usr/local/bin/git-up:23:in `<main>'
```

**Comment by williamn** [comment]
I just had this same problem. Here is how I reproduce this issue

1. Create a directory
1. Add a git remote origin
1. `git up`
1. Error

How I fix the issue

1. `git pull origin master`
1. `git up`
1. No error appear

It seems that this was caused by git-up failed to read HEAD revision, as I got this when I run `git log`

`fatal: bad default revision 'HEAD'`

**Comment by alvintownsend** [comment]
+1

```git pull origin master``` corrected the issue for me as well.

**Comment by tehmaspc** [comment]
+1 on `git up` failing on empty git repo (w/ no branches). Should fail gracefully.
