### ISSUE TITLE
Ruby error on running git-up

### ISSUE THREAD

**Issue by Imunhatep** [aanand/git-up#112]
```
/home/user/.gem/ruby/gems/git-up-0.5.12/lib/git-up.rb:240:in `rescue in check_bundler': uninitialized constant GitUp::Bundler (NameError)
    from /home/user/.gem/ruby/gems/git-up-0.5.12/lib/git-up.rb:235:in `check_bundler'
    from /home/user/.gem/ruby/gems/git-up-0.5.12/lib/git-up.rb:27:in `run'
    from /home/user/.gem/ruby/gems/git-up-0.5.12/bin/git-up:5:in `<top (required)>'
    from /home/user/bin/git-up:23:in `load'
    from /home/user/bin/git-up:23:in `<main>'
```

**Comment by Imunhatep** [comment]
$ gem install bundler
$ bundle install

That fixed the issue, but why it happened?
